version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    environment:
      - DATABASE_URL=postgresql://postgres:vTrDLmISQPajxoWRTiWPOykaMDbqGgzl@caboose.proxy.rlwy.net:14363/railway
      - APP_ENV=prod
      - APP_SECRET=your_secret_key
      - PORT=80  # Assure-toi que le port est bien défini (Railway le gérera automatiquement)
    volumes:
      - .:/var/www/html
    ports:
      - "$PORT:$PORT"  # Mappe le port dynamique à la même valeur
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
